#! /usr/bin/python3

import subprocess as sp
sp.call("clear", shell=True)
print("|^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^|")
print("|_______________________METHUKI'S SCHEDULE_________________________|                   |")
print("|__________________________________________________________________|    ~~LEGEND~~     |")
print("|SUNDAY___MONDAY__TUESDAY__WEDNESDAY__THURSDAY__FRIDAY___SATURDAY__|                   |")
print("|Washro.|Washro.|Washro. | Washro.  |   PT    |   DPA  |___________|   FT = free time  |")
print("| Read  |  DPA  |  DPA   |  DPA     | Washro. |Washroom|___________|  PL = piano lesson|")
print("|Breakf.|Breakf.|Breakf. |  Breakf. |  DPA    |  Stu/D |___________|  ft = family time |")
print("| Dress |Pack up|Pack Up |   D      | breakf. |Breakfa.|___________|   D = duolingo    |")
print("|Swimmi.|   D   |   D    | Pack Up  | Pack Up |Pack up |___________|   HW = homework   |")
print("|Laun/FT|SCHOOL | SCHOOL | SCHOOL   | SCHOOL  |______|___________|   st = study      |")
print("|  DPA  |  DPA  |  DPA   |   LUNCH  |   DPA   |________|___________| PT = programming  |")
print("| Lunch | Lunch |  Lunch |    D     |  LUNCH  |________|___________| Wake up time:6:30 |")
print("|   ft  |Hmwk/st| HW/ST  |    FT    | HW/stu  |________|___________| Sleep time: 8:50  |")
print("|Ukelele|Ukelele|Ukelele!|   HW/st  |   D     |________|___________|                   |")
print("|HW/Math|  FT   | Study  |   DPA    |   FT    |________|___________| 30 min. washroom  |")
print("|   FT  | Study |  FT    | 2 Bananas|   ft    |________|___________| 20 min. eating    |")
print("|   D   | Dinner| Dinner |    PL    |   D     |________|___________|On thursdays wake  |")
print("| Study | SLEEP | SLEEP  |  Dinner  | Dinner  |________|___________| up at 5:30        |")
print("|   FT  |_______|________|  SLEEP   |  SLEEP  |________|___________|                   |")
print("| Dinner|_______|________|__________|_________|________|___________|                   |")
print("|   FT  |_______|________|__________|_________|________|___________|                   |")
print("| SLEEP |_______|________|__________|_________|________|___________|                   |")
print("|_______|_______|________|__________|_________|________|___________|___________________|")
