#! /bin/bash

./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
./musHistPractice.py 10
sleep 1
./termsPractice.py 10
sleep 1
